/**
 * VIN model lookup for: Renault, Dacia, Peugeot, Citroën, DS, Opel,
 * Ford, Toyota, Lexus, Honda, Hyundai, Kia, Volvo, Jaguar, Land Rover,
 * Alfa Romeo, Fiat, Ferrari, Lamborghini, Nissan, Mazda, Subaru, Mitsubishi
 *
 * Key = WMI (3) + VIN[3] + VIN[4]  →  positions 4-5 of VIN
 */
export const OTHER_MODELS: Record<string, string> = {

  // ═══════════════════════════════════════════════════════════
  // RENAULT (VF1)
  // ═══════════════════════════════════════════════════════════
  'VF1AA': 'Clio',
  'VF1AB': 'Clio RS',
  'VF1AC': 'Clio E-Tech',
  'VF1BA': 'Megane',
  'VF1BB': 'Megane RS',
  'VF1BC': 'Megane E-Tech',
  'VF1CA': 'Laguna',
  'VF1CB': 'Laguna Coupé',
  'VF1DA': 'Espace',
  'VF1EA': 'Scenic',
  'VF1EB': 'Grand Scenic',
  'VF1EC': 'Scenic E-Tech',
  'VF1FA': 'Trafic',
  'VF1GA': 'Kangoo',
  'VF1GB': 'Kangoo E-Tech',
  'VF1HA': 'Kadjar',
  'VF1JA': 'Koleos',
  'VF1KA': 'Captur',
  'VF1KB': 'Captur E-Tech',
  'VF1LA': 'Twingo',
  'VF1LB': 'Twingo Electric',
  'VF1MA': 'Zoe',
  'VF1NA': 'Arkana',
  'VF1PA': 'Austral',
  'VF1QA': 'Rafale',
  'VF1RA': 'Talisman',
  'VF1SA': 'Safrane',

  // ═══════════════════════════════════════════════════════════
  // DACIA (UU1, UU3)
  // ═══════════════════════════════════════════════════════════
  'UU1AA': 'Duster',
  'UU1AB': 'Duster 4WD',
  'UU1BA': 'Logan',
  'UU1BB': 'Logan MCV',
  'UU1CA': 'Sandero',
  'UU1CB': 'Sandero Stepway',
  'UU1DA': 'Lodgy',
  'UU1EA': 'Dokker',
  'UU1FA': 'Spring',
  'UU1GA': 'Jogger',
  'UU1HA': 'Bigster',
  'UU3AA': 'Duster',
  'UU3BA': 'Logan',
  'UU3CA': 'Sandero',

  // ═══════════════════════════════════════════════════════════
  // PEUGEOT (VF3)
  // ═══════════════════════════════════════════════════════════
  'VF3AA': '108',
  'VF3BA': '208',
  'VF3BB': '208 GT',
  'VF3BC': 'e-208',
  'VF3CA': '308',
  'VF3CB': '308 SW',
  'VF3CC': '308 GT',
  'VF3DA': '408',
  'VF3EA': '508',
  'VF3EB': '508 SW',
  'VF3EC': '508 PSE',
  'VF3FA': '2008',
  'VF3FB': 'e-2008',
  'VF3GA': '3008',
  'VF3GB': '3008 GT',
  'VF3GC': 'e-3008',
  'VF3HA': '5008',
  'VF3HB': 'e-5008',
  'VF3JA': 'Rifter',
  'VF3KA': 'Traveller',
  'VF3LA': 'Partner',
  'VF3MA': 'Expert',

  // ═══════════════════════════════════════════════════════════
  // CITROËN (VF7, VF8) + DS (VF9, VR7)
  // ═══════════════════════════════════════════════════════════
  'VF7AA': 'C1',
  'VF7BA': 'C3',
  'VF7BB': 'C3 Aircross',
  'VF7BC': 'ë-C3',
  'VF7CA': 'C4',
  'VF7CB': 'ë-C4',
  'VF7CC': 'C4 X',
  'VF7DA': 'C5',
  'VF7DB': 'C5 X',
  'VF7DC': 'C5 Aircross',
  'VF7EA': 'C3 Picasso',
  'VF7EB': 'C4 Picasso',
  'VF7EC': 'Grand C4 Picasso',
  'VF7FA': 'Berlingo',
  'VF7GA': 'SpaceTourer',
  'VF7HA': 'Jumpy',
  'VF8AA': 'C-Elysée',
  'VF9AA': 'DS 3',
  'VF9AB': 'DS 3 Crossback',
  'VF9BA': 'DS 4',
  'VF9BB': 'DS 4 Crossback',
  'VF9CA': 'DS 5',
  'VF9DA': 'DS 7 Crossback',
  'VF9EA': 'DS 9',
  'VR7AA': 'DS 3',
  'VR7BA': 'DS 7',

  // ═══════════════════════════════════════════════════════════
  // OPEL / VAUXHALL (W0L, TMA, X0L)
  // ═══════════════════════════════════════════════════════════
  'W0LAA': 'Corsa',
  'W0LAB': 'Corsa-e',
  'W0LAC': 'Corsa OPC',
  'W0LBA': 'Astra',
  'W0LBB': 'Astra Sports Tourer',
  'W0LBC': 'Astra GSe',
  'W0LBD': 'Astra Electric',
  'W0LCA': 'Insignia',
  'W0LCB': 'Insignia Sports Tourer',
  'W0LCC': 'Insignia Grand Sport',
  'W0LDA': 'Mokka',
  'W0LDB': 'Mokka-e',
  'W0LEA': 'Crossland',
  'W0LEB': 'Crossland X',
  'W0LFA': 'Grandland',
  'W0LFB': 'Grandland X',
  'W0LFC': 'Grandland GSe',
  'W0LGA': 'Zafira',
  'W0LGB': 'Zafira Tourer',
  'W0LHA': 'Vectra',
  'W0LHB': 'Vectra Caravan',
  'W0LJA': 'Meriva',
  'W0LKA': 'Combo',
  'W0LLA': 'Vivaro',
  'W0LMA': 'Cascada',
  'W0LNA': 'Adam',
  'W0LPA': 'Karl / Viva',
  'TMAAA': 'Corsa',
  'TMABA': 'Astra',

  // ═══════════════════════════════════════════════════════════
  // FORD — European (WF0)
  // ═══════════════════════════════════════════════════════════
  'WF0AA': 'Fiesta',
  'WF0AB': 'Fiesta ST',
  'WF0BA': 'Focus',
  'WF0BB': 'Focus ST',
  'WF0BC': 'Focus RS',
  'WF0CA': 'Mondeo',
  'WF0CB': 'Mondeo Hybrid',
  'WF0DA': 'Kuga',
  'WF0DB': 'Kuga PHEV',
  'WF0EA': 'EcoSport',
  'WF0FA': 'Puma',
  'WF0FB': 'Puma ST',
  'WF0GA': 'Galaxy',
  'WF0HA': 'S-Max',
  'WF0JA': 'Mustang Mach-E',
  'WF0KA': 'Explorer',
  'WF0LA': 'Tourneo Connect',
  'WF0MA': 'Transit Connect',
  'WF0NA': 'Transit Custom',
  'WF0PA': 'Transit',

  // ═══════════════════════════════════════════════════════════
  // TOYOTA — European (SB1, WBA, JT2, JTD, JTE, JTM, JTN, JT3)
  // ═══════════════════════════════════════════════════════════
  'SB1AA': 'Yaris',
  'SB1AB': 'Yaris GR',
  'SB1AC': 'Yaris Cross',
  'SB1BA': 'Corolla',
  'SB1BB': 'Corolla Touring Sports',
  'SB1CA': 'C-HR',
  'SB1CB': 'C-HR PHEV',
  'SB1DA': 'RAV4',
  'SB1DB': 'RAV4 PHEV',
  'SB1EA': 'Camry',
  'SB1FA': 'Highlander',
  'SB1GA': 'Land Cruiser',
  'SB1GB': 'Land Cruiser Prado',
  'SB1HA': 'bZ4X',
  'SB1JA': 'Aygo X',
  'SB1KA': 'Proace',
  'JTDBA': 'Corolla',
  'JTDCA': 'Avensis',
  'JTDDA': 'RAV4',
  'JTDEA': 'Auris',
  'JTDFA': 'Yaris',
  'JTDGA': 'C-HR',
  'JTDHA': 'Hilux',
  'JTDJA': 'Land Cruiser',

  // LEXUS
  'JTJAA': 'UX',
  'JTJBA': 'NX',
  'JTJCA': 'RX',
  'JTJDA': 'GX',
  'JTJEA': 'LX',
  'JTJFA': 'IS',
  'JTJGA': 'ES',
  'JTJHA': 'GS',
  'JTJJA': 'LS',
  'JTJKA': 'RC',
  'JTJLA': 'LC',
  'JTJMA': 'CT',
  'JTJPA': 'RZ',

  // ═══════════════════════════════════════════════════════════
  // HONDA (JHM, 19X)
  // ═══════════════════════════════════════════════════════════
  'JHMAA': 'Jazz',
  'JHMAB': 'Jazz Crosstar',
  'JHMAC': 'Jazz e:HEV',
  'JHMBA': 'Civic',
  'JHMBB': 'Civic Type R',
  'JHMBC': 'Civic e:HEV',
  'JHMCA': 'CR-V',
  'JHMCB': 'CR-V e:PHEV',
  'JHMDA': 'HR-V',
  'JHMEA': 'ZR-V',
  'JHMFA': 'e:Ny1',
  'JHMGA': 'Legend',
  'JHMHA': 'Accord',

  // ═══════════════════════════════════════════════════════════
  // HYUNDAI (KMH, KMF, TMF)
  // ═══════════════════════════════════════════════════════════
  'KMHAA': 'i10',
  'KMHAB': 'i10 N Line',
  'KMHBA': 'i20',
  'KMHBB': 'i20 N',
  'KMHBC': 'i20 N Line',
  'KMHCA': 'i30',
  'KMHCB': 'i30 N',
  'KMHCC': 'i30 Fastback',
  'KMHCD': 'i30 SW',
  'KMHDA': 'i40',
  'KMHDB': 'i40 Tourer',
  'KMHEA': 'Elantra',
  'KMHFA': 'Tucson',
  'KMHFB': 'Tucson PHEV',
  'KMHGA': 'Santa Fe',
  'KMHGB': 'Santa Fe PHEV',
  'KMHHA': 'Kona',
  'KMHHB': 'Kona Electric',
  'KMHJA': 'IONIQ',
  'KMHJB': 'IONIQ 5',
  'KMHJC': 'IONIQ 6',
  'KMHJD': 'IONIQ 9',
  'KMHKA': 'Staria',
  'KMHLA': 'Bayon',
  'KMHMA': 'Nexo',
  'KMFBA': 'i20',
  'KMFCA': 'i30',
  'KMFFA': 'Tucson',

  // ═══════════════════════════════════════════════════════════
  // KIA (KNA, KND, U5Y, U6Y)
  // ═══════════════════════════════════════════════════════════
  'KNAAA': 'Picanto',
  'KNAAB': 'Picanto GT Line',
  'KNABA': 'Rio',
  'KNABB': 'Rio GT Line',
  'KNACA': 'Ceed',
  'KNACB': 'Ceed GT',
  'KNACC': 'ProCeed',
  'KNACD': 'XCeed',
  'KNADA': 'Stonic',
  'KNAEA': 'Soul',
  'KNAEB': 'Soul EV',
  'KNAFA': 'Sportage',
  'KNAFB': 'Sportage PHEV',
  'KNAGA': 'Niro',
  'KNAGB': 'Niro EV',
  'KNAGC': 'Niro PHEV',
  'KNAHA': 'Sorento',
  'KNAHB': 'Sorento PHEV',
  'KNAJA': 'EV6',
  'KNAJB': 'EV6 GT',
  'KNAKA': 'EV9',
  'KNALA': 'Carnival',
  'KNAMA': 'Telluride',
  'KNANA': 'EV3',
  'KNDAA': 'Picanto',
  'KNDCA': 'Ceed',
  'KNDFA': 'Sportage',
  'KNDHA': 'Sorento',

  // ═══════════════════════════════════════════════════════════
  // VOLVO (YV1, YV2, YV4, VSK)
  // ═══════════════════════════════════════════════════════════
  'YV1AA': 'S40',
  'YV1BA': 'S60',
  'YV1BB': 'S60 Recharge',
  'YV1CA': 'S80',
  'YV1DA': 'S90',
  'YV1DB': 'S90 Recharge',
  'YV1EA': 'V40',
  'YV1EB': 'V40 Cross Country',
  'YV1FA': 'V60',
  'YV1FB': 'V60 Cross Country',
  'YV1FC': 'V60 Recharge',
  'YV1GA': 'V70',
  'YV1HA': 'V90',
  'YV1HB': 'V90 Cross Country',
  'YV1HC': 'V90 Recharge',
  'YV1JA': 'XC40',
  'YV1JB': 'XC40 Recharge',
  'YV1KA': 'XC60',
  'YV1KB': 'XC60 Recharge',
  'YV1LA': 'XC90',
  'YV1LB': 'XC90 Recharge',
  'YV1MA': 'C30',
  'YV1NA': 'C40 Recharge',
  'YV1PA': 'EX30',
  'YV1QA': 'EX40',
  'YV1RA': 'EX90',

  // ═══════════════════════════════════════════════════════════
  // JAGUAR (SAJ) + LAND ROVER (SAL, SALJ, SALV, SALW)
  // ═══════════════════════════════════════════════════════════
  'SAJAA': 'XE',
  'SAJAB': 'XF',
  'SAJAC': 'XF Sportbrake',
  'SAJAD': 'XJ',
  'SAJAE': 'E-Pace',
  'SAJAF': 'F-Pace',
  'SAJAG': 'F-Pace SVR',
  'SAJAH': 'I-Pace',
  'SAJAJ': 'F-Type',
  'SAJAK': 'F-Type R',
  'SAJAL': 'XK',
  'SALAA': 'Defender 90',
  'SALAB': 'Defender 110',
  'SALAC': 'Defender 130',
  'SALAD': 'Discovery',
  'SALAE': 'Discovery Sport',
  'SALAF': 'Freelander',
  'SALAG': 'Range Rover',
  'SALAH': 'Range Rover Sport',
  'SALAJ': 'Range Rover Velar',
  'SALAK': 'Range Rover Evoque',
  'SALAL': 'Range Rover SVAutobiography',

  // ═══════════════════════════════════════════════════════════
  // ALFA ROMEO (ZAR) + FIAT (ZFA) + LANCIA (ZLA)
  // ═══════════════════════════════════════════════════════════
  'ZARAA': 'Giulia',
  'ZARAB': 'Giulia GTA',
  'ZARAC': 'Giulia Quadrifoglio',
  'ZARAD': 'Stelvio',
  'ZARAE': 'Stelvio Quadrifoglio',
  'ZARAF': 'Tonale',
  'ZARAG': 'Tonale PHEV',
  'ZARAH': 'Giulietta',
  'ZARAJ': 'MiTo',
  'ZARAK': '4C',
  'ZARAL': '4C Spider',
  'ZARAM': 'Junior',
  'ZFAAA': '500',
  'ZFAAB': '500e',
  'ZFAAC': '500 Abarth',
  'ZFABA': 'Panda',
  'ZFABB': 'Panda 4x4',
  'ZFABC': 'Panda Cross',
  'ZFACA': 'Tipo',
  'ZFACB': 'Tipo Cross',
  'ZFACC': 'Tipo SW',
  'ZFADA': 'Doblo',
  'ZFAEA': 'Bravo',
  'ZFAFA': '500X',
  'ZFAFB': '500L',
  'ZFAGA': 'Punto',
  'ZFAHA': 'Grande Punto',
  'ZFAJA': '600',
  'ZLABA': 'Ypsilon',
  'ZLABB': 'Ypsilon Hybrid',

  // ═══════════════════════════════════════════════════════════
  // NISSAN (JN1, JN6, VNK, VSK)
  // ═══════════════════════════════════════════════════════════
  'JN1AA': 'Micra',
  'JN1BA': 'Juke',
  'JN1BB': 'Juke Hybrid',
  'JN1CA': 'Qashqai',
  'JN1CB': 'Qashqai e-Power',
  'JN1DA': 'X-Trail',
  'JN1DB': 'X-Trail e-Power',
  'JN1EA': 'Leaf',
  'JN1FA': 'Ariya',
  'JN1GA': 'Note',
  'JN1HA': 'Navara',
  'JN1JA': 'Pathfinder',
  'JN1KA': 'Murano',
  'JN1LA': '370Z',
  'JN1MA': 'GT-R',
  'JN6AA': 'Navara',

  // ═══════════════════════════════════════════════════════════
  // MAZDA (JM1, JMZ)
  // ═══════════════════════════════════════════════════════════
  'JM1AA': 'Mazda2',
  'JM1AB': 'Mazda2 Hybrid',
  'JM1BA': 'Mazda3',
  'JM1BB': 'Mazda3 Fastback',
  'JM1CA': 'Mazda6',
  'JM1CB': 'Mazda6 SW',
  'JM1DA': 'CX-3',
  'JM1EA': 'CX-30',
  'JM1FA': 'CX-5',
  'JM1FB': 'CX-5 Skyactiv-X',
  'JM1GA': 'CX-60',
  'JM1GB': 'CX-60 PHEV',
  'JM1HA': 'CX-80',
  'JM1JA': 'CX-90',
  'JM1KA': 'MX-5',
  'JM1LA': 'MX-30',
  'JM1MA': 'MX-30 R-EV',

  // ═══════════════════════════════════════════════════════════
  // SUBARU (JF1, JF2)
  // ═══════════════════════════════════════════════════════════
  'JF1AA': 'Impreza',
  'JF1AB': 'Impreza WRX',
  'JF1AC': 'WRX STI',
  'JF1BA': 'Forester',
  'JF1BB': 'Forester e-Boxer',
  'JF1CA': 'Outback',
  'JF1CB': 'Outback e-Boxer',
  'JF1DA': 'XV / Crosstrek',
  'JF1DB': 'XV e-Boxer',
  'JF1EA': 'Legacy',
  'JF1FA': 'BRZ',
  'JF1GA': 'Solterra',
  'JF2BA': 'Forester',
  'JF2CA': 'Outback',
  'JF2DA': 'XV',

  // ═══════════════════════════════════════════════════════════
  // FERRARI (ZFF) + LAMBORGHINI (ZHW) + MASERATI (ZAM)
  // ═══════════════════════════════════════════════════════════
  'ZFFAA': 'Roma',
  'ZFFAB': 'Roma Spider',
  'ZFFAC': '296 GTB',
  'ZFFAD': '296 GTS',
  'ZFFAE': '296 GT3',
  'ZFFBA': 'Portofino',
  'ZFFBB': 'Portofino M',
  'ZFFCA': 'SF90 Stradale',
  'ZFFCB': 'SF90 Spider',
  'ZFFDA': '812 Superfast',
  'ZFFDB': '812 GTS',
  'ZFFDC': '812 Competizione',
  'ZFFEA': 'F8 Tributo',
  'ZFFEB': 'F8 Spider',
  'ZFFFA': 'Purosangue',
  'ZFFGA': 'GTC4 Lusso',
  'ZFFHA': '488 GTB',
  'ZHWAA': 'Urus',
  'ZHWAB': 'Urus Performante',
  'ZHWAC': 'Urus S',
  'ZHWBA': 'Huracán',
  'ZHWBB': 'Huracán Evo',
  'ZHWBC': 'Huracán STO',
  'ZHWCA': 'Aventador',
  'ZHWCB': 'Aventador S',
  'ZHWCC': 'Revuelto',
  'ZAMAA': 'Ghibli',
  'ZAMAB': 'Ghibli Hybrid',
  'ZAMBA': 'Levante',
  'ZAMBB': 'Levante GT',
  'ZAMCA': 'Quattroporte',
  'ZAMDA': 'Grecale',
  'ZAMDB': 'Grecale GT',
  'ZAMEA': 'GranTurismo',
  'ZAMFA': 'MC20',

  // ═══════════════════════════════════════════════════════════
  // TESLA (5YJ, SFZ, LRW, 7G2, XP7)
  // ═══════════════════════════════════════════════════════════
  '5YJAA': 'Model S',
  '5YJAB': 'Model S Plaid',
  '5YJCA': 'Model X',
  '5YJCB': 'Model X Plaid',
  '5YJEAA': 'Model 3',
  '5YJFA': 'Model 3 Performance',
  '5YJGA': 'Model Y',
  '5YJGB': 'Model Y Performance',
  'SFZAA': 'Model 3',
  'SFZBA': 'Model Y',
  'LRWAA': 'Model 3',
  'LRWBA': 'Model Y',
  'LRWCA': 'Model S',
  'LRWDA': 'Model X',

  // ═══════════════════════════════════════════════════════════
  // GENESIS (KMT, MAL)
  // ═══════════════════════════════════════════════════════════
  'KMTAA': 'G70',
  'KMTAB': 'G70 Shooting Brake',
  'KMTBA': 'G80',
  'KMTCA': 'G90',
  'KMTDA': 'GV70',
  'KMTDB': 'GV70 Electrified',
  'KMTEA': 'GV80',
  'KMTFA': 'GV60',
  'KMTGA': 'Electrified G80',
};
