/**
 * VIN model lookup — remaining manufacturers without dedicated files:
 * Volvo (YV1/YV4), Jaguar (SAJ), Land Rover (SAL),
 * Alfa Romeo (ZAR), Fiat (ZFA), Lancia (ZLA),
 * Nissan (JN1/JN6/JN8/VNV), Infiniti (JNK),
 * Mazda (JM1/JM4/JMZ), Subaru (JF1/JF2),
 * Mitsubishi (JMB/JA3/JA4), Suzuki (JS1-JS4),
 * Tesla (5YJ/SFZ/LRW/XP7), SsangYong (KPT/KLA),
 * McLaren (SBM), Aston Martin (SCF), Rolls-Royce (SCA),
 * Bentley (SCB), Lotus (SCC), DeLorean (SCE),
 * Ford EU additional plants (WF1/SFA/VS6),
 * Alpine (VFA), DS additional (VR1/VR8)
 *
 * Key = WMI (3) + VIN[3] + VIN[4]  →  positions 4-5 of VIN
 */
import { ModelInfo } from './types';

export const OTHER_DB: Record<string, ModelInfo> = {

  // ═══════════════════════════════════════════════════════════
  // VOLVO (YV1, YV4)
  // ═══════════════════════════════════════════════════════════
  'YV1AA': { model: 'S40', generation: 'P1', start: 2004, end: 2012 },
  'YV1BA': { model: 'S60', generation: 'P3', start: 2010 },
  'YV1BB': { model: 'S60 Recharge', generation: 'P3', start: 2020 },
  'YV1CA': { model: 'S80', generation: 'P3', start: 2006, end: 2016 },
  'YV1DA': { model: 'S90', generation: 'SPA', start: 2016 },
  'YV1DB': { model: 'S90 Recharge', generation: 'SPA', start: 2020 },
  'YV1EA': { model: 'V40', generation: 'P1', start: 2012, end: 2019 },
  'YV1EB': { model: 'V40 Cross Country', generation: 'P1', start: 2012, end: 2019 },
  'YV1FA': { model: 'V60', generation: 'SPA', start: 2018 },
  'YV1FB': { model: 'V60 Cross Country', generation: 'SPA', start: 2018 },
  'YV1FC': { model: 'V60 Recharge', generation: 'SPA', start: 2020 },
  'YV1GA': { model: 'V70', generation: 'P3', start: 2007, end: 2016 },
  'YV1HA': { model: 'V90', generation: 'SPA', start: 2016 },
  'YV1HB': { model: 'V90 Cross Country', generation: 'SPA', start: 2017 },
  'YV1HC': { model: 'V90 Recharge', generation: 'SPA', start: 2021 },
  'YV1JA': { model: 'XC40', generation: 'CMA', start: 2017 },
  'YV1JB': { model: 'XC40 Recharge', generation: 'CMA', start: 2020 },
  'YV1KA': { model: 'XC60', generation: 'SPA', start: 2017 },
  'YV1KB': { model: 'XC60 Recharge', generation: 'SPA', start: 2021 },
  'YV1LA': { model: 'XC90', generation: 'SPA', start: 2015 },
  'YV1LB': { model: 'XC90 Recharge', generation: 'SPA', start: 2020 },
  'YV1MA': { model: 'C30', generation: 'P1', start: 2006, end: 2013 },
  'YV1NA': { model: 'C40 Recharge', generation: 'CMA', start: 2021 },
  'YV1PA': { model: 'EX30', generation: 'SEA', start: 2023 },
  'YV1QA': { model: 'EX40', generation: 'CMA', start: 2023 },
  'YV1RA': { model: 'EX90', generation: 'SPA2', start: 2024 },
  // YV4 = newer SUV/electric platform (2019+)
  'YV4JA': { model: 'XC40', generation: 'CMA', start: 2019 },
  'YV4JB': { model: 'XC40 Recharge', generation: 'CMA', start: 2020 },
  'YV4KA': { model: 'XC60', generation: 'SPA', start: 2019 },
  'YV4KB': { model: 'XC60 Recharge', generation: 'SPA', start: 2021 },
  'YV4LA': { model: 'XC90', generation: 'SPA', start: 2019 },
  'YV4LB': { model: 'XC90 Recharge', generation: 'SPA', start: 2020 },
  'YV4MA': { model: 'XC90', generation: 'SPA', start: 2022 },
  'YV4NA': { model: 'C40 Recharge', generation: 'CMA', start: 2021 },
  'YV4PA': { model: 'EX30', generation: 'SEA', start: 2023 },
  'YV4RA': { model: 'EX90', generation: 'SPA2', start: 2024 },
  // 4-char fallback keys for YV4
  'YV4J': { model: 'XC40', generation: 'CMA', start: 2017 },
  'YV4K': { model: 'XC60', generation: 'SPA', start: 2017 },
  'YV4L': { model: 'XC90', generation: 'SPA', start: 2015 },
  'YV4M': { model: 'XC90', generation: 'SPA', start: 2022 },

  // ═══════════════════════════════════════════════════════════
  // JAGUAR (SAJ) + LAND ROVER (SAL)
  // ═══════════════════════════════════════════════════════════
  'SAJAA': { model: 'XE', generation: 'X760', start: 2015 },
  'SAJAB': { model: 'XF', generation: 'X260', start: 2015 },
  'SAJAC': { model: 'XF Sportbrake', generation: 'X260', start: 2017 },
  'SAJAD': { model: 'XJ', generation: 'X351', start: 2009, end: 2019 },
  'SAJAE': { model: 'E-Pace', generation: 'X540', start: 2017 },
  'SAJAF': { model: 'F-Pace', generation: 'X761', start: 2016 },
  'SAJAG': { model: 'F-Pace SVR', generation: 'X761', start: 2018 },
  'SAJAH': { model: 'I-Pace', generation: 'X590', start: 2018 },
  'SAJAJ': { model: 'F-Type', generation: 'X152', start: 2013 },
  'SAJAK': { model: 'F-Type R', generation: 'X152', start: 2014 },
  'SAJAL': { model: 'XK', generation: 'X150', start: 2006, end: 2015 },
  'SALAA': { model: 'Defender 90', generation: 'L663', start: 2020 },
  'SALAB': { model: 'Defender 110', generation: 'L663', start: 2020 },
  'SALAC': { model: 'Defender 130', generation: 'L663', start: 2022 },
  'SALAD': { model: 'Discovery', generation: 'L462', start: 2016 },
  'SALAE': { model: 'Discovery Sport', generation: 'L550', start: 2014 },
  'SALAF': { model: 'Freelander', generation: 'L359', start: 2006, end: 2014 },
  'SALAG': { model: 'Range Rover', generation: 'L460', start: 2021 },
  'SALAH': { model: 'Range Rover Sport', generation: 'L461', start: 2022 },
  'SALAJ': { model: 'Range Rover Velar', generation: 'L560', start: 2017 },
  'SALAK': { model: 'Range Rover Evoque', generation: 'L551', start: 2019 },
  'SALAL': { model: 'Range Rover SVAutobiography', generation: 'L405', start: 2013, end: 2021 },

  // ═══════════════════════════════════════════════════════════
  // ALFA ROMEO (ZAR) + FIAT (ZFA) + LANCIA (ZLA)
  // ═══════════════════════════════════════════════════════════
  'ZARAA': { model: 'Giulia', generation: '952', start: 2016 },
  'ZARAB': { model: 'Giulia GTA', generation: '952', start: 2021 },
  'ZARAC': { model: 'Giulia Quadrifoglio', generation: '952', start: 2016 },
  'ZARAD': { model: 'Stelvio', generation: '949', start: 2017 },
  'ZARAE': { model: 'Stelvio Quadrifoglio', generation: '949', start: 2017 },
  'ZARAF': { model: 'Tonale', generation: '965', start: 2022 },
  'ZARAG': { model: 'Tonale PHEV', generation: '965', start: 2023 },
  'ZARAH': { model: 'Giulietta', generation: '940', start: 2010, end: 2021 },
  'ZARAJ': { model: 'MiTo', generation: '955', start: 2008, end: 2018 },
  'ZARAK': { model: '4C', generation: '960', start: 2013, end: 2020 },
  'ZARAL': { model: '4C Spider', generation: '960', start: 2015, end: 2020 },
  'ZARAM': { model: 'Junior', generation: '976', start: 2024 },
  'ZFAAA': { model: '500', generation: '312', start: 2007 },
  'ZFAAB': { model: '500e', generation: '332', start: 2020 },
  'ZFAAC': { model: '500 Abarth', generation: '312', start: 2008 },
  'ZFABA': { model: 'Panda', generation: '312', start: 2012 },
  'ZFABB': { model: 'Panda 4x4', generation: '312', start: 2012 },
  'ZFABC': { model: 'Panda Cross', generation: '312', start: 2014 },
  'ZFACA': { model: 'Tipo', generation: '356', start: 2015 },
  'ZFACB': { model: 'Tipo Cross', generation: '356', start: 2020 },
  'ZFACC': { model: 'Tipo SW', generation: '357', start: 2016 },
  'ZFADA': { model: 'Doblo', generation: '263', start: 2010 },
  'ZFAEA': { model: 'Bravo', generation: '198', start: 2007, end: 2014 },
  'ZFAFA': { model: '500X', generation: '334', start: 2014 },
  'ZFAFB': { model: '500L', generation: '351', start: 2012 },
  'ZFAGA': { model: 'Punto', generation: '199', start: 2005, end: 2018 },
  'ZFAHA': { model: 'Grande Punto', generation: '199', start: 2005, end: 2012 },
  'ZFAJA': { model: '600', generation: '181', start: 2023 },
  'ZLABA': { model: 'Ypsilon', generation: '843', start: 2011 },
  'ZLABB': { model: 'Ypsilon Hybrid', generation: '843', start: 2021 },

  // ═══════════════════════════════════════════════════════════
  // NISSAN (JN1, JN6, JN8) + INFINITI (JNK)
  // ═══════════════════════════════════════════════════════════
  'JN1AA': { model: 'Micra', generation: 'K14', start: 2017 },
  'JN1BA': { model: 'Juke', generation: 'F16', start: 2019 },
  'JN1BB': { model: 'Juke Hybrid', generation: 'F16', start: 2021 },
  'JN1CA': { model: 'Qashqai', generation: 'J12', start: 2021 },
  'JN1CB': { model: 'Qashqai e-Power', generation: 'J12', start: 2022 },
  'JN1DA': { model: 'X-Trail', generation: 'T33', start: 2021 },
  'JN1DB': { model: 'X-Trail e-Power', generation: 'T33', start: 2022 },
  'JN1EA': { model: 'Leaf', generation: 'ZE1', start: 2017 },
  'JN1FA': { model: 'Ariya', generation: 'FE0', start: 2021 },
  'JN1GA': { model: 'Note', generation: 'E13', start: 2020 },
  'JN1HA': { model: 'Navara', generation: 'D23', start: 2015 },
  'JN1JA': { model: 'Pathfinder', generation: 'R52', start: 2021 },
  'JN1KA': { model: 'Murano', generation: 'Z52', start: 2014 },
  'JN1LA': { model: '370Z', generation: 'Z34', start: 2009, end: 2021 },
  'JN1MA': { model: 'GT-R', generation: 'R35', start: 2007 },
  'JN6AA': { model: 'Navara', generation: 'D23', start: 2015 },
  'JNKAA': { model: 'Q30', generation: 'H15', start: 2016, end: 2019 },
  'JNKBA': { model: 'Q50', generation: 'V37', start: 2013 },
  'JNKCA': { model: 'Q60', generation: 'V37', start: 2016 },
  'JNKDA': { model: 'QX30', generation: 'H15', start: 2016, end: 2019 },
  'JNKEA': { model: 'QX50', generation: 'J55', start: 2018 },
  'JNKFA': { model: 'QX55', generation: 'J55', start: 2021 },
  'JNKGA': { model: 'QX60', generation: 'L50', start: 2021 },
  'JNKHA': { model: 'QX70', generation: 'S51', start: 2013, end: 2017 },
  'JNKJA': { model: 'QX80', generation: 'Z62', start: 2014 },
  // Nissan UK/France (VNV)
  'VNVAA': { model: 'Micra', generation: 'K14', start: 2017 },
  'VNVBA': { model: 'Juke', generation: 'F16', start: 2019 },
  'VNVBB': { model: 'Juke Hybrid', generation: 'F16', start: 2021 },
  'VNVCA': { model: 'Qashqai', generation: 'J12', start: 2021 },
  'VNVCB': { model: 'Qashqai e-Power', generation: 'J12', start: 2022 },
  'VNVDA': { model: 'X-Trail', generation: 'T33', start: 2021 },
  'VNVDB': { model: 'X-Trail e-Power', generation: 'T33', start: 2022 },
  'VNVEA': { model: 'Leaf', generation: 'ZE1', start: 2017 },
  'VNVFA': { model: 'Ariya', generation: 'FE0', start: 2021 },

  // ═══════════════════════════════════════════════════════════
  // MAZDA (JM1, JM4, JMZ)
  // ═══════════════════════════════════════════════════════════
  'JM1AA': { model: 'Mazda2', generation: 'DJ', start: 2014 },
  'JM4AA': { model: 'Mazda2', generation: 'DJ', start: 2014 },
  'JM1AB': { model: 'Mazda2 Hybrid', generation: 'DJ', start: 2022 },
  'JM4AB': { model: 'Mazda2 Hybrid', generation: 'DJ', start: 2022 },
  'JM1BA': { model: 'Mazda3', generation: 'BP', start: 2019 },
  'JM4BA': { model: 'Mazda3', generation: 'BP', start: 2019 },
  'JM1BB': { model: 'Mazda3 Fastback', generation: 'BP', start: 2019 },
  'JM4BB': { model: 'Mazda3 Fastback', generation: 'BP', start: 2019 },
  'JM1BP': { model: 'Mazda3', generation: 'BP', start: 2019 },
  'JM4BP': { model: 'Mazda3', generation: 'BP', start: 2019 },
  'JM1CA': { model: 'Mazda6', generation: 'GJ', start: 2012, end: 2023 },
  'JM4CA': { model: 'Mazda6', generation: 'GJ', start: 2012, end: 2023 },
  'JM1CB': { model: 'Mazda6 SW', generation: 'GJ', start: 2013, end: 2023 },
  'JM4CB': { model: 'Mazda6 SW', generation: 'GJ', start: 2013, end: 2023 },
  'JM1DA': { model: 'CX-3', generation: 'DK', start: 2015 },
  'JM4DA': { model: 'CX-3', generation: 'DK', start: 2015 },
  'JM1EA': { model: 'CX-30', generation: 'DM', start: 2019 },
  'JM4EA': { model: 'CX-30', generation: 'DM', start: 2019 },
  'JM1FA': { model: 'CX-5', generation: 'KF', start: 2017 },
  'JM4FA': { model: 'CX-5', generation: 'KF', start: 2017 },
  'JM1FB': { model: 'CX-5 Skyactiv-X', generation: 'KF', start: 2019 },
  'JM4FB': { model: 'CX-5 Skyactiv-X', generation: 'KF', start: 2019 },
  'JM1GA': { model: 'CX-60', generation: 'KH', start: 2022 },
  'JM4GA': { model: 'CX-60', generation: 'KH', start: 2022 },
  'JM1GB': { model: 'CX-60 PHEV', generation: 'KH', start: 2022 },
  'JM4GB': { model: 'CX-60 PHEV', generation: 'KH', start: 2022 },
  'JM1HA': { model: 'CX-80', generation: 'KH', start: 2024 },
  'JM4HA': { model: 'CX-80', generation: 'KH', start: 2024 },
  'JM1JA': { model: 'CX-90', generation: 'KH', start: 2023 },
  'JM4JA': { model: 'CX-90', generation: 'KH', start: 2023 },
  'JM1KA': { model: 'MX-5', generation: 'ND', start: 2015 },
  'JM4KA': { model: 'MX-5', generation: 'ND', start: 2015 },
  'JM1LA': { model: 'MX-30', generation: 'DR', start: 2020 },
  'JM4LA': { model: 'MX-30', generation: 'DR', start: 2020 },
  'JM1MA': { model: 'MX-30 R-EV', generation: 'DR', start: 2023 },
  'JM4MA': { model: 'MX-30 R-EV', generation: 'DR', start: 2023 },

  // ═══════════════════════════════════════════════════════════
  // SUBARU (JF1, JF2)
  // ═══════════════════════════════════════════════════════════
  'JF1AA': { model: 'Impreza', generation: 'GK/GT', start: 2016 },
  'JF1AB': { model: 'Impreza WRX', generation: 'VB', start: 2022 },
  'JF1AC': { model: 'WRX STI', generation: 'VA', start: 2014, end: 2021 },
  'JF1BA': { model: 'Forester', generation: 'SK', start: 2018 },
  'JF1BB': { model: 'Forester e-Boxer', generation: 'SK', start: 2019 },
  'JF1CA': { model: 'Outback', generation: 'BT', start: 2019 },
  'JF1CB': { model: 'Outback e-Boxer', generation: 'BT', start: 2019 },
  'JF1DA': { model: 'Crosstrek', generation: 'GU', start: 2023 },
  'JF1DB': { model: 'XV e-Boxer', generation: 'GT', start: 2019, end: 2023 },
  'JF1EA': { model: 'Legacy', generation: 'BN/BS', start: 2014 },
  'JF1FA': { model: 'BRZ', generation: 'ZD8', start: 2021 },
  'JF1GA': { model: 'Solterra', generation: 'E-SUBARU', start: 2022 },
  'JF2BA': { model: 'Forester', generation: 'SK', start: 2018 },
  'JF2CA': { model: 'Outback', generation: 'BT', start: 2019 },
  'JF2DA': { model: 'Crosstrek', generation: 'GU', start: 2023 },

  // ═══════════════════════════════════════════════════════════
  // MITSUBISHI (JMB, JA3, JA4)
  // ═══════════════════════════════════════════════════════════
  'JMBAA': { model: 'Colt', generation: 'Z30', start: 2023 },
  'JMBBA': { model: 'Lancer', generation: 'CY', start: 2007, end: 2017 },
  'JMBBB': { model: 'Lancer Evolution', generation: 'CZ', start: 2007, end: 2016 },
  'JMBCA': { model: 'Galant', generation: 'DJ', start: 2004, end: 2012 },
  'JMBDA': { model: 'Eclipse Cross', generation: 'GK', start: 2017 },
  'JMBDB': { model: 'Eclipse Cross PHEV', generation: 'GK', start: 2021 },
  'JMBEA': { model: 'Outlander', generation: 'GN', start: 2021 },
  'JMBEB': { model: 'Outlander PHEV', generation: 'GN', start: 2021 },
  'JMBEC': { model: 'Outlander Sport', generation: 'GA', start: 2010 },
  'JMBFA': { model: 'ASX', generation: 'GA', start: 2010 },
  'JMBFB': { model: 'ASX PHEV', generation: 'GA', start: 2023 },
  'JMBGA': { model: 'Pajero', generation: 'V80', start: 2006, end: 2021 },
  'JMBGB': { model: 'Pajero Sport', generation: 'QF', start: 2015 },
  'JMBHA': { model: 'L200', generation: 'KL', start: 2015 },
  'JMBJA': { model: 'Space Star', generation: 'A05', start: 2012 },
  'JA3AA': { model: 'Colt', generation: 'Z30', start: 2023 },
  'JA3BA': { model: 'Lancer', generation: 'CY', start: 2007, end: 2017 },
  'JA3CA': { model: 'Eclipse', generation: 'D54', start: 2006, end: 2011 },
  'JA4AA': { model: 'Outlander', generation: 'GN', start: 2021 },
  'JA4AB': { model: 'Outlander PHEV', generation: 'GN', start: 2021 },
  'JA4BA': { model: 'ASX', generation: 'GA', start: 2010 },

  // ═══════════════════════════════════════════════════════════
  // SUZUKI (JS1, JS2, JS3, JS4)
  // ═══════════════════════════════════════════════════════════
  'JS1AA': { model: 'Swift', generation: 'AZ', start: 2017 },
  'JS1AB': { model: 'Swift Sport', generation: 'AZ', start: 2017 },
  'JS1BA': { model: 'Baleno', generation: 'FW', start: 2022 },
  'JS1CA': { model: 'Vitara', generation: 'LY', start: 2015 },
  'JS1CB': { model: 'Vitara SHVS', generation: 'LY', start: 2018 },
  'JS1DA': { model: 'S-Cross', generation: 'JY', start: 2021 },
  'JS1DB': { model: 'S-Cross Hybrid', generation: 'JY', start: 2022 },
  'JS1EA': { model: 'Ignis', generation: 'FF', start: 2016 },
  'JS1FA': { model: 'Jimny', generation: 'JB74', start: 2018 },
  'JS1GA': { model: 'Across', generation: 'YB', start: 2020 },
  'JS1HA': { model: 'Swace', generation: 'XB', start: 2020 },
  'JS2AA': { model: 'Swift', generation: 'AZ', start: 2017 },
  'JS2CA': { model: 'Vitara', generation: 'LY', start: 2015 },
  'JS2DA': { model: 'S-Cross', generation: 'JY', start: 2021 },
  'JS3AA': { model: 'Swift', generation: 'AZ', start: 2017 },
  'JS3CA': { model: 'Vitara', generation: 'LY', start: 2015 },
  'JS3FA': { model: 'Jimny', generation: 'JB74', start: 2018 },
  'JS4AA': { model: 'Swift', generation: 'AZ', start: 2017 },
  'JS4CA': { model: 'Vitara', generation: 'LY', start: 2015 },
  'JS4FA': { model: 'Jimny', generation: 'JB74', start: 2018 },

  // ═══════════════════════════════════════════════════════════
  // TESLA (5YJ=US Fremont, SFZ=UK legacy, LRW=Shanghai, XP7=Giga Berlin)
  // ═══════════════════════════════════════════════════════════
  '5YJS':  { model: 'Model S', start: 2012 },
  '5YJSA': { model: 'Model S', start: 2012 },
  '5YJSE': { model: 'Model S', start: 2012 },
  '5YJX':  { model: 'Model X', start: 2015 },
  '5YJXC': { model: 'Model X', start: 2015 },
  '5YJ3':  { model: 'Model 3', start: 2017 },
  '5YJ3E': { model: 'Model 3', start: 2017 },
  '5YJY':  { model: 'Model Y', start: 2020 },
  '5YJYG': { model: 'Model Y', start: 2020 },
  '5YJYC': { model: 'Model Y Performance', start: 2020 },
  'SFZS':  { model: 'Model S', start: 2012 },
  'SFZ3':  { model: 'Model 3', start: 2017 },
  'SFZY':  { model: 'Model Y', start: 2020 },
  'LRW3':  { model: 'Model 3', start: 2020 },
  'LRWY':  { model: 'Model Y', start: 2021 },
  'LRWS':  { model: 'Model S', start: 2012 },
  'LRWX':  { model: 'Model X', start: 2015 },
  'XP7Y':  { model: 'Model Y', generation: 'Giga Berlin', start: 2022 },
  'XP73':  { model: 'Model 3', generation: 'Giga Berlin', start: 2023 },

  // ═══════════════════════════════════════════════════════════
  // SSANGYONG (KPT, KLA)
  // ═══════════════════════════════════════════════════════════
  'KPTAA': { model: 'Tivoli', start: 2015 },
  'KPTAB': { model: 'Tivoli Electric', start: 2020 },
  'KPTBA': { model: 'Korando', generation: 'C300', start: 2019 },
  'KPTBB': { model: 'Korando e-Motion', generation: 'C300', start: 2021 },
  'KPTCA': { model: 'Rexton', generation: 'Y450', start: 2017 },
  'KPTCB': { model: 'Rexton Sport', generation: 'Y450', start: 2018 },
  'KPTDA': { model: 'Musso', generation: 'Q201', start: 2018 },
  'KLAAA': { model: 'Tivoli', start: 2015 },
  'KLABA': { model: 'Korando', generation: 'C300', start: 2019 },
  'KLACA': { model: 'Rexton', generation: 'Y450', start: 2017 },

  // ═══════════════════════════════════════════════════════════
  // MCLAREN (SBM)
  // ═══════════════════════════════════════════════════════════
  'SBMAA': { model: '720S', generation: 'P14', start: 2017 },
  'SBMAB': { model: '720S Spider', generation: 'P14', start: 2018 },
  'SBMBA': { model: '765LT', generation: 'P14', start: 2020 },
  'SBMBB': { model: '765LT Spider', generation: 'P14', start: 2021 },
  'SBMCA': { model: 'GT', generation: 'M80S', start: 2019 },
  'SBMDA': { model: 'Artura', generation: 'M88S', start: 2021 },
  'SBMDB': { model: 'Artura Spider', generation: 'M88S', start: 2023 },
  'SBMEA': { model: '570S', generation: 'P13', start: 2015, end: 2021 },
  'SBMEB': { model: '570GT', generation: 'P13', start: 2016, end: 2021 },
  'SBMFA': { model: '600LT', generation: 'P13', start: 2018, end: 2021 },

  // ═══════════════════════════════════════════════════════════
  // ASTON MARTIN (SCF)
  // ═══════════════════════════════════════════════════════════
  'SCFAA': { model: 'DB11', generation: 'AM818', start: 2016 },
  'SCFAB': { model: 'DB11 Volante', generation: 'AM818', start: 2017 },
  'SCFBA': { model: 'DB12', generation: 'AM823', start: 2023 },
  'SCFBB': { model: 'DB12 Volante', generation: 'AM823', start: 2023 },
  'SCFCA': { model: 'Vantage', generation: 'AM814', start: 2018 },
  'SCFCB': { model: 'Vantage Roadster', generation: 'AM814', start: 2020 },
  'SCFDA': { model: 'DBS', generation: 'AM818', start: 2018 },
  'SCFDB': { model: 'DBS Superleggera', generation: 'AM818', start: 2018, end: 2022 },
  'SCFEA': { model: 'DBX', generation: 'AM827', start: 2020 },
  'SCFEB': { model: 'DBX707', generation: 'AM827', start: 2022 },
  'SCFFA': { model: 'Valkyrie', generation: 'AM036', start: 2021 },
  'SCFGA': { model: 'Vanquish', generation: 'AM835', start: 2024 },

  // ═══════════════════════════════════════════════════════════
  // ROLLS-ROYCE (SCA) / BENTLEY (SCB) / LOTUS (SCC) / DELOREAN (SCE)
  // ═══════════════════════════════════════════════════════════
  'SCAAA': { model: 'Phantom', generation: 'RR12', start: 2017 },
  'SCAAB': { model: 'Phantom EWB', generation: 'RR12', start: 2017 },
  'SCABA': { model: 'Ghost', generation: 'RR12', start: 2020 },
  'SCABB': { model: 'Ghost EWB', generation: 'RR12', start: 2020 },
  'SCACA': { model: 'Wraith', generation: 'RR11', start: 2013, end: 2023 },
  'SCACB': { model: 'Wraith Black Badge', generation: 'RR11', start: 2016, end: 2023 },
  'SCADA': { model: 'Dawn', generation: 'RR11', start: 2015, end: 2023 },
  'SCAEA': { model: 'Cullinan', generation: 'RR12', start: 2018 },
  'SCAEB': { model: 'Cullinan Black Badge', generation: 'RR12', start: 2020 },
  'SCAFA': { model: 'Spectre', generation: 'RR12', start: 2023 },
  'SCBAA': { model: 'Continental GT', generation: 'G3', start: 2017 },
  'SCBAB': { model: 'Continental GT Convertible', generation: 'G3', start: 2018 },
  'SCBBA': { model: 'Flying Spur', generation: 'G3', start: 2019 },
  'SCBCA': { model: 'Bentayga', generation: 'G1', start: 2015 },
  'SCBCB': { model: 'Bentayga EWB', generation: 'G1', start: 2022 },
  'SCBDA': { model: 'Mulsanne', generation: 'G1', start: 2010, end: 2020 },
  'SCCAA': { model: 'Emira', generation: 'V6/I4', start: 2022 },
  'SCCBA': { model: 'Evija', start: 2023 },
  'SCCCA': { model: 'Elise', generation: 'S3', start: 2010, end: 2021 },
  'SCCDA': { model: 'Exige', generation: 'S3', start: 2011, end: 2021 },
  'SCEAA': { model: 'DMC-12', start: 1981, end: 1982 },

  // ═══════════════════════════════════════════════════════════
  // ALPINE (VFA)
  // ═══════════════════════════════════════════════════════════
  'VFAAA': { model: 'A110', generation: 'B110', start: 2017 },
  'VFAAB': { model: 'A110 S', generation: 'B110', start: 2019 },
  'VFAAC': { model: 'A110 R', generation: 'B110', start: 2022 },
  'VFABA': { model: 'A290', generation: 'B290', start: 2024 },
  'VFACA': { model: 'A310', start: 2025 },

  // ═══════════════════════════════════════════════════════════
  // DS AUTOMOBILES additional (VR1, VR8)
  // ═══════════════════════════════════════════════════════════
  'VR1AA': { model: 'DS 3', generation: 'D34', start: 2019 },
  'VR1AB': { model: 'DS 3 Crossback', generation: 'D34', start: 2019 },
  'VR1AC': { model: 'DS 3 E-Tense', generation: 'D34', start: 2020 },
  'VR1BA': { model: 'DS 4', generation: 'D43', start: 2021 },
  'VR1BB': { model: 'DS 4 E-Tense', generation: 'D43', start: 2022 },
  'VR1CA': { model: 'DS 5', generation: 'D52', start: 2011, end: 2018 },
  'VR1DA': { model: 'DS 7 Crossback', generation: 'D74', start: 2017 },
  'VR1DB': { model: 'DS 7 E-Tense', generation: 'D74', start: 2020 },
  'VR1EA': { model: 'DS 9', generation: 'D94', start: 2021 },
  'VR8AA': { model: 'DS 3', generation: 'D34', start: 2019 },
  'VR8AB': { model: 'DS 3 Crossback', generation: 'D34', start: 2019 },
  'VR8AC': { model: 'DS 3 E-Tense', generation: 'D34', start: 2020 },
  'VR8BA': { model: 'DS 4', generation: 'D43', start: 2021 },
  'VR8BB': { model: 'DS 4 E-Tense', generation: 'D43', start: 2022 },
  'VR8CA': { model: 'DS 5', generation: 'D52', start: 2011, end: 2018 },
  'VR8DA': { model: 'DS 7', generation: 'D74', start: 2017 },
  'VR8DB': { model: 'DS 7 E-Tense', generation: 'D74', start: 2020 },
  'VR8EA': { model: 'DS 9', generation: 'D94', start: 2021 },
  'VR8EB': { model: 'DS 9 E-Tense', generation: 'D94', start: 2022 },

  // ═══════════════════════════════════════════════════════════
  // FORD EU additional plants (WF1, SFA, VS6)
  // ═══════════════════════════════════════════════════════════
  'WF1AA': { model: 'Fiesta', generation: 'MK8', start: 2017, end: 2023 },
  'WF1BA': { model: 'Focus', generation: 'MK4', start: 2018 },
  'WF1CA': { model: 'Mondeo', generation: 'MK5', start: 2014, end: 2022 },
  'WF1DA': { model: 'Kuga', generation: 'MK3', start: 2019 },
  'WF1EA': { model: 'EcoSport', generation: 'MK2', start: 2013, end: 2022 },
  'WF1FA': { model: 'Puma', generation: 'MK2', start: 2019 },
  'SFAAA': { model: 'Fiesta', generation: 'MK8', start: 2017, end: 2023 },
  'SFABA': { model: 'Focus', generation: 'MK4', start: 2018 },
  'SFACA': { model: 'Mondeo', generation: 'MK5', start: 2014, end: 2022 },
  'SFADA': { model: 'Kuga', generation: 'MK3', start: 2019 },
  'SFAFA': { model: 'Puma', generation: 'MK2', start: 2019 },
  'VS6AA': { model: 'Fiesta', generation: 'MK8', start: 2017, end: 2023 },
  'VS6BA': { model: 'Focus', generation: 'MK4', start: 2018 },
  'VS6FA': { model: 'Puma', generation: 'MK2', start: 2019 },
};
